// <auto-generated />
namespace Moviegram.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Movie_AdditionalColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Movie_AdditionalColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201905122225409_Movie_AdditionalColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
